### PR TITLE
User tests

### PR DESCRIPTION
**Pull request by jjalfaro9**
Finished implementing User Tests. They all passed!

### CODE REVIEW

**Comment by jjalfaro9** [comment]
retry

**Comment by JohnStarich** [comment]
retry

**Comment by JohnStarich** [comment]
Please review my change! I normally wouldn't push changes on top of yours, but I figured since you're out of town.. 😄

**Comment by jjalfaro9** [comment]
retry

**Comment by jjalfaro9** [comment]
retry

**Comment by jjalfaro9** [comment]
retry

**Comment by jjalfaro9** [comment]
retry

**Comment by jjalfaro9** [comment]
retry

**Comment by jjalfaro9** [comment]
LGTM :+1:

**Pull request merged**
