### PR TITLE
FriendRoutess

### PR DESCRIPTION
**Pull request by jjalfaro9**
Working on friends routes. need to implement jpost and jget. added index to username in user class, so we can search that, changed load method in abstractmodel to take in a class, so we can avoid nullptr exception

### CODE REVIEW

**Comment by jjalfaro9** [comment]
retry

**Comment by jjalfaro9** [comment]
retry

**Comment by jeremycastillo** [comment]
LGTM 👍

**Comment by JohnStarich** [comment]
LGTM 👍

**Pull request merged**
